local_backend: true
backend:
  name: git-gateway
  branch: master
media_folder: content/site_images
collections:
  - label: Dogs
    name: the_dogs
    label_singular: Dog
    folder: "dogs"
    editor:
      preview: false
    create: true
    media_folder: ""
    summary: "{{name}}"
    identifier_field: name
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    path: "{{slug}}/index"
    fields:
      - label: Name
        name: name
      - label: Breed
        name: breed
        widget: object
        fields:
          - label: English
            name: en
          - label: Español              
            name: es
      - label: Sex
        name: sex
        widget: "select"
        options:
          - { label: "Male", value: "m" }
          - { label: "Female", value: "f" }
      - label: Date of Birth
        name: dob
        widget: datetime
        time_format: false
        date_format: "DD/MM/YYYY"
      - label: Date came in
        name: date_came_in
        widget: datetime
        time_format: false
        date_format: "DD/MM/YYYY"
      - label: Photos
        name: photos
        hint: Put main photo first
        widget: list
        max: 4
        summary: "{{fields.photo}}"
        collapsed: false
        fields:
          - label: Photo
            name: photo
            widget: image
      - label: PPP?
        name: ppp
        widget: select
        options: ["Yes", "No"]
        default: "No"
      - label: Available?
        name: available
        hint: If the dog has been reserved or adopted, choose 'No'.
        widget: select
        options: ["Yes", "No"]
        default: "Yes"
      - label: Description
        name: description
        widget: object
        fields:
          - label: English
            name: en
            widget: text
          - label: Español              
            name: es
            widget: text
      - label: Sociability
        name: sociability
        widget: object
        fields:
          - label: Other dogs
            name: dogs
            widget: select
            options: ["Yes", "No", "TBC"]
            default: "Yes"
          - label: Cats 
            name: cats
            widget: select
            options: ["Yes", "No", "TBC"]
            default: "Yes"
          - label: Children
            name: children
            widget: select
            options: ["Yes", "No", "TBC"]
            default: "Yes"
  - label: Pages 
    name: content
    media_folder: ./site_images
    public_folder: site_images
    editor:
      preview: false
    files:
      - label: Homepage
        name: homepage
        file: content/home.md
        fields:
          - label: Images (Landscape)
            name: homepage_images_landscape
            hint: Will typically show on desktop devices
            widget: list
            collapsed: false
            minimize_collapsed: true
            fields:
              - label: Image
                name: image
                widget: image
          - label: Images (Portrait)
            name: homepage_images_portrait
            hint: Will typically show on mobile devices
            widget: list
            collapsed: false
            minimize_collapsed: true
            fields:
              - label: Image
                name: image
                widget: image
          - label: Heading
            name: homepage_heading
            widget: object
            fields:
              - label: English
                name: en
              - label: Español              
                name: es
          - label: Lead
            name: homepage_lead
            widget: object
            fields:
              - label: English
                name: en
              - label: Español              
                name: es
          - label: Call to Action (CTA) 
            name: homepage_cta
            widget: object
            fields:
              - label: English
                name: en
              - label: Español              
                name: es
      - label: The Dogs
        name: the_dogs
        file: content/the-dogs.md
        fields:
          - label: Heading banner
            name: heading_banner
            widget: object
            fields:
              - label: Intro text
                name: intro_text
                widget: object
                fields:
                  - label: English
                    name: en
                  - label: Español              
                    name: es
              - label: Background image
                name: background_image
                widget: image
          - label: PPP Text
            name: ppp_text
            hint: Shows when hovering over question mark on dog profile
            widget: object
            fields:
              - label: English
                name: en
                widget: text
              - label: Español              
                name: es
                widget: text
      - label: Adopt 
        name: adopt
        file: content/adopt.md
        fields:
          - label: Heading banner
            name: heading_banner
            widget: object
            fields:
              - label: Intro text
                name: intro_text
                widget: object
                fields:
                  - label: English
                    name: en
                  - label: Español              
                    name: es
              - label: Background image
                name: background_image
                widget: image
          - label: Page content
            name: content
            widget: object
            fields:
              - label: English
                name: en
                widget: markdown
                buttons: ["bold", "italic", "link", "heading-one", "bulleted-list", "numbered-list"]
                editor_components: []
                modes: ["rich_text"]
              - label: Español              
                name: es
                widget: markdown
                buttons: ["bold", "italic", "link", "heading-one", "bulleted-list", "numbered-list"]
                editor_components: []
                modes: ["rich_text"]
      - label: Foster 
        name: foster
        file: content/foster.md
        fields:
          - label: Heading banner
            name: heading_banner
            widget: object
            fields:
              - label: Intro text
                name: intro_text
                widget: object
                fields:
                  - label: English
                    name: en
                  - label: Español              
                    name: es
              - label: Background image
                name: background_image
                widget: image
          - label: Page content
            name: content
            widget: object
            fields:
              - label: English
                name: en
                widget: markdown
                buttons: ["bold", "italic", "link", "heading-one", "bulleted-list", "numbered-list"]
                editor_components: []
                modes: ["rich_text"]
              - label: Español              
                name: es
                widget: markdown
                buttons: ["bold", "italic", "link", "heading-one", "bulleted-list", "numbered-list"]
                editor_components: []
                modes: ["rich_text"]
      - label: Donate 
        name: donate
        file: content/donate.md
        fields:
          - label: Heading banner
            name: heading_banner
            widget: object
            fields:
              - label: Intro text
                name: intro_text
                widget: object
                fields:
                  - label: English
                    name: en
                  - label: Español              
                    name: es
              - label: Background image
                name: background_image
                widget: image
          - label: Page content
            name: content
            widget: object
            fields:
              - label: English
                name: en
                widget: markdown
                buttons: ["bold", "italic", "link", "heading-one", "bulleted-list", "numbered-list"]
                editor_components: []
                modes: ["rich_text"]
              - label: Español              
                name: es
                widget: markdown
                buttons: ["bold", "italic", "link", "heading-one", "bulleted-list", "numbered-list"]
                editor_components: []
                modes: ["rich_text"]
          - label: PayPal donate button text
            name: paypal_btn_text
            widget: object
            fields:
              - label: English
                name: en
              - label: Español              
                name: es
          - label: Teaming button text
            name: teaming_btn_text
            widget: object
            fields:
              - label: English
                name: en
              - label: Español              
                name: es
          - label: Teaming button link
            name: teaming_btn_link
          - label: Bank account details
            name: bank_account_details
            widget: object
            fields:
              - label: Name of bank
                name: bank_name
              - label: Account name
                name: account_name
              - label: Account number
                name: account_number
              - label: SWIFT/BIC
                name: swift_bic
      - label: Volunteer 
        name: volunteer
        file: content/volunteer.md
        fields:
          - label: Heading banner
            name: heading_banner
            widget: object
            fields:
              - label: Intro text
                name: intro_text
                widget: object
                fields:
                  - label: English
                    name: en
                  - label: Español              
                    name: es
              - label: Background image
                name: background_image
                widget: image
          - label: Page content
            name: content
            widget: object
            fields:
              - label: English
                name: en
                widget: markdown
                buttons: ["bold", "italic", "link", "heading-one", "bulleted-list", "numbered-list"]
                editor_components: []
                modes: ["rich_text"]
              - label: Español              
                name: es
                widget: markdown
                buttons: ["bold", "italic", "link", "heading-one", "bulleted-list", "numbered-list"]
                editor_components: []
                modes: ["rich_text"]
      - label: About
        name: about
        file: content/about.md
        fields:
          - label: Heading banner
            name: heading_banner
            widget: object
            fields:
              - label: Intro text
                name: intro_text
                widget: object
                fields:
                  - label: English
                    name: en
                  - label: Español              
                    name: es
              - label: Background image
                name: background_image
                widget: image
          - label: Page content
            name: content
            widget: object
            fields:
              - label: English
                name: en
                widget: markdown
                buttons: ["bold", "italic", "link", "heading-one", "bulleted-list", "numbered-list"]
                editor_components: []
                modes: ["rich_text"]
              - label: Español              
                name: es
                widget: markdown
                buttons: ["bold", "italic", "link", "heading-one", "bulleted-list", "numbered-list"]
                editor_components: []
                modes: ["rich_text"]
      - label: Contact
        name: contact
        file: content/contact.md
        fields:
          - label: Heading banner
            name: heading_banner
            widget: object
            fields:
              - label: Intro text
                name: intro_text
                widget: object
                fields:
                  - label: English
                    name: en
                  - label: Español              
                    name: es
              - label: Background image
                name: background_image
                widget: image
          - label: Contact warning
            name: contact_warning
            widget: object
            fields:
              - label: Heading
                name: heading
                widget: object
                fields:
                - label: English
                  name: en
                - label: Español              
                  name: es
              - label: Text 
                name: text
                widget: object
                fields:
                - label: English
                  name: en
                  widget: text
                - label: Español              
                  name: es
                  widget: text
          - label: Common queries
            name: common_queries
            widget: list
            fields:
              - label: Query
                name: query
                widget: object
                fields:
                  - label: English
                    name: en
                  - label: Español              
                    name: es
              - label: Response
                name: response
                widget: object
                fields:
                  - label: English
                    name: en
                    widget: text
                  - label: Español              
                    name: es
                    widget: text
          - label: Contact button introduction
            name: contact_button_intro
            widget: object
            fields:
              - label: English
                name: en
                widget: text
              - label: Español              
                name: es
                widget: text
          - label: Contact form introduction
            name: contact_form_intro
            widget: object
            fields:
              - label: English
                name: en
                widget: text
              - label: Español              
                name: es
                widget: text
          - label: Contact form fields
            name: contact_form_fields
            widget: object
            fields:
              - label: Name
                name: name
                widget: object
                fields:
                  - label: English
                    name: en
                  - label: Español              
                    name: es
              - label: Email 
                name: email
                widget: object
                fields:
                  - label: English
                    name: en
                  - label: Español              
                    name: es
              - label: Phone
                name: phone
                widget: object
                fields:
                  - label: English
                    name: en
                  - label: Español              
                    name: es
              - label: Message
                name: message
                widget: object
                fields:
                  - label: English
                    name: en
                  - label: Español              
                    name: es
              - label: Send
                name: send
                widget: object
                fields:
                  - label: English
                    name: en
                  - label: Español              
                    name: es
          - label: Contact form submit notifications
            name: contact_form_notifications
            widget: object
            fields:
              - label: Message sent
                name: message_sent
                widget: object
                fields:
                  - label: English
                    name: en
                  - label: Español              
                    name: es
              - label: Message not sent
                name: message_not_sent
                widget: object
                fields:
                  - label: English
                    name: en
                  - label: Español              
                    name: es
  - label: Other 
    name: legal_and_location
    media_folder: ./site_images
    public_folder: site_images
    editor:
      preview: false
    files:
      - label: Contact and social media
        name: contact_and_social
        file: content/contact_and_social.md
        fields:
          - label: Email address
            name: email_address
          - label: Facebook username
            name: facebook_username
          - label: Instagram username
            name: instagram_username
      - label: Location
        name: location
        file: content/location.md
        fields:
          - label: Address
            name: address
            widget: object
            fields:
              - label: Street address
                name: street_address
              - label: Town/City
                name: town_city
              - label: Postcode
                name: postcode
          - label: GPS
            name: gps
            widget: object
            fields:
              - label: Latitude
                name: latitude
              - label: Longitude
                name: longitude              
      - label: Legal notices
        name: legal_notice
        file: content/legal.md
        fields:
          - label: Charity declaration
            name: charity_declaration
            widget: object
            fields:
              - label: English
                name: en
                widget: text
              - label: Español              
                name: es
                widget: text